[features]
seeds = false
skip-lint = false

[programs.devnet]
data_store = "3CoF2STeHokdFvTjhjq5ymoVCDrhAhdawpR2Co3ipNWK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/mateo/.config/solana/id.json"

[scripts]
create_data = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/create_data.ts"
modify_data = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/modify_data.ts"